#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent
# Spec: 029-resolve-merge-conflicts-with-selective-staging

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Spec: Selective Staging for Merge Conflicts"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Navigate to project root
cd "$(dirname "$0")/../../.."
PROJECT_ROOT=$(pwd)

echo ""
echo "Project root: $PROJECT_ROOT"
echo ""

# Check if node_modules exist
if [ ! -d "$PROJECT_ROOT/apps/frontend/node_modules" ]; then
    echo -e "${YELLOW}Installing frontend dependencies...${NC}"
    cd "$PROJECT_ROOT/apps/frontend" && npm install
fi

# ============================================
# START FRONTEND SERVICE
# ============================================

echo ""
echo -e "${YELLOW}Starting Frontend Dev Server...${NC}"
echo ""

cd "$PROJECT_ROOT/apps/frontend"

# Start frontend in foreground (Electron app)
npm run dev

# ============================================
# SUMMARY
# ============================================
# Frontend: Electron app with React renderer
# Dev command: cd apps/frontend && npm run dev
# Port: 3000 (renderer), Electron window
