#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 001 - Add Accordion Behavior to Done Kanban Items

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Spec: Add Accordion Behavior to Done Kanban Items"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

# Frontend (primary service for this task)
echo ""
echo "Starting Frontend service..."
cd apps/frontend || exit 1

# Ensure dependencies are installed
if [ ! -d "node_modules" ]; then
    echo "Installing frontend dependencies..."
    npm install
fi

# Start frontend dev server
npm run dev &
FRONTEND_PID=$!

# Wait for frontend to be ready
wait_for_service 3000 "Frontend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend: http://localhost:3000"
echo ""
echo "Frontend PID: $FRONTEND_PID"
echo ""
echo "To stop the server:"
echo "  kill $FRONTEND_PID"
echo ""
echo "Note: Backend is not required for this UI-only feature."
echo "      The frontend can run standalone for development."
echo ""
