#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for: CLAUDE.md Project Setting
# Spec: 051-add-claude-md-project-setting-for-agent-context-cu

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# PROJECT INFO
# ============================================

echo ""
echo "Project: Turret (Electron App)"
echo "Type: Monorepo"
echo ""

# ============================================
# PREREQUISITES CHECK
# ============================================

echo "Checking prerequisites..."

# Check Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}Node.js not found. Please install Node.js${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Node.js $(node -v)${NC}"

# Check npm
if ! command -v npm &> /dev/null; then
    echo -e "${RED}npm not found. Please install npm${NC}"
    exit 1
fi
echo -e "${GREEN}✓ npm $(npm -v)${NC}"

# Check Python
if ! command -v python &> /dev/null; then
    echo -e "${RED}Python not found. Please install Python${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Python $(python --version 2>&1 | cut -d' ' -f2)${NC}"

# ============================================
# INSTALL DEPENDENCIES
# ============================================

echo ""
echo "Installing dependencies..."

# Install frontend dependencies
cd apps/frontend
if [ ! -d "node_modules" ]; then
    echo "Installing frontend dependencies..."
    npm install
else
    echo -e "${GREEN}✓ Frontend dependencies already installed${NC}"
fi
cd ../..

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting services..."

# Frontend (Electron App)
echo "Starting Frontend (Electron + Vite)..."
cd apps/frontend && npm run dev &
FRONTEND_PID=$!
cd ../..

# Wait for Vite dev server
wait_for_service 3000 "Frontend (Vite)"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend: http://localhost:3000 (Electron app with Vite)"
echo ""
echo "This feature involves:"
echo "  - Frontend: UI toggle, env var passing, type definitions"
echo "  - Backend: CLAUDE.md file loading and system prompt injection"
echo ""
echo "Files to modify:"
echo "  - apps/frontend/src/shared/types/project.ts"
echo "  - apps/frontend/src/shared/constants/config.ts"
echo "  - apps/frontend/src/shared/i18n/locales/en/settings.json"
echo "  - apps/frontend/src/shared/i18n/locales/fr/settings.json"
echo "  - apps/frontend/src/renderer/components/project-settings/GeneralSettings.tsx"
echo "  - apps/frontend/src/main/agent/agent-process.ts"
echo "  - apps/backend/core/client.py"
echo ""
echo "Press Ctrl+C to stop all services"
echo ""

# Keep script running
wait $FRONTEND_PID
