#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Spec 004
# Feature: AI-Powered Task Refinement Button

set -e

echo "========================================"
echo "Starting Development Environment"
echo "AI-Powered Task Refinement Feature"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# IMPORTANT: THIS IS AN ELECTRON DESKTOP APP
# ============================================
# Unlike typical web apps, this project uses Electron
# which bundles both frontend and backend together.
#
# The "backend" is the Electron main process (Python)
# The "frontend" is the Electron renderer process (React/TypeScript)
#
# Starting the app launches BOTH processes automatically.
# ============================================

echo ""
echo "Project Type: Electron Desktop Application"
echo "Architecture: Monorepo (apps/frontend + apps/backend)"
echo ""

# ============================================
# START ELECTRON APP
# ============================================

echo "Starting Electron app (includes frontend + backend)..."
echo "Command: cd apps/frontend && npm run dev"
echo ""
echo -e "${YELLOW}Note: Backend (Python main process) starts automatically${NC}"
echo ""

cd apps/frontend
npm run dev &
FRONTEND_PID=$!

# Wait for Electron to start (it doesn't expose a port in dev mode)
echo "Waiting for Electron to initialize..."
sleep 5

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Electron App: Running (PID: $FRONTEND_PID)"
echo "  Frontend (Renderer): React/TypeScript (Vite)"
echo "  Backend (Main): Python (Electron main process)"
echo ""
echo "To test the AI refinement feature:"
echo "  1. Click the '+' button to create a new task"
echo "  2. Enter a brief description (e.g., 'add dark mode')"
echo "  3. Click 'Refine with AI' button"
echo "  4. Observe fields auto-populate"
echo ""
echo "To stop: Press Ctrl+C or run 'kill $FRONTEND_PID'"
echo ""

# Keep script running
wait $FRONTEND_PID
